name: test linux

on:
  push:
    paths:
      - 'linux'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: download my linux repo
      env:
        comment_num: git rev-parse HEAD:linux
      run: wget -O testlinux https://github.com/C-limlim/archive/${comment_num}.zip
      
    - name: unzip my linux
      run: unzip testlinux
      
    - name: install deph
      run: ./install-deph.sh
      
    - name: build-linux
      run: ./buile-linux.sh linux-${sha} tinyconfig
