# This is a basic workflow to help you get started with Actions

name: push event that contains changes in the commit number of the submodule linux

# Controls when the workflow will run
on: 
  push:
    paths:
      - 'linux'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
  - uses: actions/checkout@v2
    with:
      submodules: true
      
  - name: get comment
     run: git rev-parse HEAD:linux
     
  - name: download my linux repository
  run: wget -O testlinux https://github.com/C-limlim/archive/&{GITHUB_SHA}.zip
  
  - name: unzip my linux
     run: unzip testlinux
  
  - name: install-deph
     run: ./install-deph.sh
     
  - name: buile-linux
     run: ./build-linux.sh linux-${sha} tinyconfig
   


      
      
