# This is a basic workflow to help you get started with Actions

name: push event that contains changes in the commit number of the submodule linux

# Controls when the workflow will run
on: 
  push:
    paths:
      - 'linux'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
 
    runs-on: ubuntu-latest
		
    steps:
    - uses: actions/checkout@v2
    - name: download my linux repository
      run: wget -O testlinux https://github.com/C-limlim/linux/archive/${GITHUB_SHA}.zip

    - name: unzip my linux
      run: 
        unzip testlinux
        
    - name: 
      
      
